# Generated by Django 4.1.1 on 2022-10-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seccion",
            old_name="espacio",
            new_name="lugar",
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="otro_espacio",
        ),
    ]
