# Generated by Django 4.1.1 on 2022-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_articulo_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="fecha",
            field=models.DateField(null=True),
        ),
    ]
