# Generated by Django 4.1.1 on 2022-10-19 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="lugares"),
        ),
        migrations.AddField(
            model_name="articulo",
            name="subtitulo",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="articulo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
