# Generated by Django 4.1.1 on 2022-10-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_articulo_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="imagen",
            field=models.ImageField(null=True, upload_to="imagenes/"),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="texto",
            field=models.TextField(null=True),
        ),
    ]
