# Generated by Django 4.1.1 on 2022-10-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_articulo_imagen_articulo_subtitulo_articulo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articulo",
            name="user",
        ),
    ]
