from django.urls import path
from blog.views import (
    ArticuloCreacion,
    ArticuloDelete,
    ArticuloDetalle,
    ArticuloUpdateView,
    ArticuloList,
    agregar_articulo,
    inicio,
    about,
    buscar_articulo,
    buscar_autor,
    buscar_seccion,
    leer_articulos,
    procesar_seccion,
    procesar_autor,
    MyLogin,
    register,
    editar_perfil,
    agregar_avatar,
)

from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", inicio, name="inicio"),
    path("inicio/", inicio, name="inicio"),
    path("about/", about, name="about"),
    path("agregar-seccion/", procesar_seccion, name="agregar-seccion"),
    path("agregar-autor/", procesar_autor, name="agregar-autor"),
    path("agregar-articulo/", agregar_articulo, name="agregar-articulo"),
    # path("agregar-articulo2/", ArticuloCreacion.as_view(), name="ArticuloNew"),
    path("articulo-nuevo/", ArticuloCreacion.as_view(), name="ArticuloNew"),
    path("articulo/list", ArticuloList.as_view(), name="ArticuloList"),
    path("articulo/<pk>'", ArticuloDetalle.as_view(), name="ArticuloDetail"),
    path("editar/<pk>", ArticuloUpdateView.as_view(), name="ArticuloUpdate"),
    path("borrar/<pk>", ArticuloDelete.as_view(), name="ArticuloDelete"),
    path("busqueda_autor/", buscar_autor, name="buscar_autor"),
    path("busqueda_articulo/", buscar_articulo, name="buscar_articulo"),
    path("busqueda_seccion/", buscar_seccion, name="buscar-seccion"),
    path("leer_articulo/", leer_articulos, name="leer-articulos"),
    path("login/", MyLogin.as_view(), name="Login"),
    path(
        "logout/",
        LogoutView.as_view(template_name="/logout.html"),
        name="Logout",
    ),
    path("register/", register, name="Register"),
    path("editar-perfil/", editar_perfil, name="EditarPerfil"),
    path("agregar-avatar/", agregar_avatar, name="AgregarAvatar"),
]
